//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> custumerID { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public Nullable<int> bookingStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
