//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Mvc;

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [AllowHtml]
        public string ContentPost { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> Author { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> UseDescription { get; set; }
        public int Seen { get; set; }
        public bool Active { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
