//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int ID { get; set; }
        public string image_Name { get; set; }
        public string image_Description { get; set; }
        public string image_Path { get; set; }
        public Nullable<int> active1 { get; set; }
    }
}
