//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.MetaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiTemplate
    {
        public int ID { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
