//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int ID { get; set; }
        public Nullable<int> bookingID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<int> detailQuantity { get; set; }
        public Nullable<double> detailPrice { get; set; }
        public Nullable<int> detailTotal { get; set; }
        public Nullable<System.DateTime> bookingStart { get; set; }
        public Nullable<System.DateTime> bookingEnd { get; set; }
        public string typeRoom { get; set; }
        public Nullable<int> roomQuantity { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
    }
}
