//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPath
    {
        public int ID { get; set; }
        public Nullable<int> accountGroupID { get; set; }
        public Nullable<int> pathID { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual Path Path { get; set; }
    }
}
